// Curated country -> primary IANA time zone list, used by the Settings page's
// Country selector to auto-fill a sensible time zone (admin can still override it).
export interface CountryTimeZone {
  country: string;
  timeZoneId: string;
}

export const COUNTRY_TIMEZONES: CountryTimeZone[] = [
  { country: 'Pakistan', timeZoneId: 'Asia/Karachi' },
  { country: 'India', timeZoneId: 'Asia/Kolkata' },
  { country: 'Bangladesh', timeZoneId: 'Asia/Dhaka' },
  { country: 'Sri Lanka', timeZoneId: 'Asia/Colombo' },
  { country: 'Nepal', timeZoneId: 'Asia/Kathmandu' },
  { country: 'Afghanistan', timeZoneId: 'Asia/Kabul' },
  { country: 'United Arab Emirates', timeZoneId: 'Asia/Dubai' },
  { country: 'Saudi Arabia', timeZoneId: 'Asia/Riyadh' },
  { country: 'Qatar', timeZoneId: 'Asia/Qatar' },
  { country: 'Kuwait', timeZoneId: 'Asia/Kuwait' },
  { country: 'Bahrain', timeZoneId: 'Asia/Bahrain' },
  { country: 'Oman', timeZoneId: 'Asia/Muscat' },
  { country: 'Turkey', timeZoneId: 'Europe/Istanbul' },
  { country: 'Iran', timeZoneId: 'Asia/Tehran' },
  { country: 'Iraq', timeZoneId: 'Asia/Baghdad' },
  { country: 'Israel', timeZoneId: 'Asia/Jerusalem' },
  { country: 'Jordan', timeZoneId: 'Asia/Amman' },
  { country: 'Egypt', timeZoneId: 'Africa/Cairo' },
  { country: 'China', timeZoneId: 'Asia/Shanghai' },
  { country: 'Hong Kong', timeZoneId: 'Asia/Hong_Kong' },
  { country: 'Japan', timeZoneId: 'Asia/Tokyo' },
  { country: 'South Korea', timeZoneId: 'Asia/Seoul' },
  { country: 'Singapore', timeZoneId: 'Asia/Singapore' },
  { country: 'Malaysia', timeZoneId: 'Asia/Kuala_Lumpur' },
  { country: 'Indonesia', timeZoneId: 'Asia/Jakarta' },
  { country: 'Thailand', timeZoneId: 'Asia/Bangkok' },
  { country: 'Vietnam', timeZoneId: 'Asia/Ho_Chi_Minh' },
  { country: 'Philippines', timeZoneId: 'Asia/Manila' },
  { country: 'Taiwan', timeZoneId: 'Asia/Taipei' },
  { country: 'United Kingdom', timeZoneId: 'Europe/London' },
  { country: 'Ireland', timeZoneId: 'Europe/Dublin' },
  { country: 'France', timeZoneId: 'Europe/Paris' },
  { country: 'Germany', timeZoneId: 'Europe/Berlin' },
  { country: 'Spain', timeZoneId: 'Europe/Madrid' },
  { country: 'Italy', timeZoneId: 'Europe/Rome' },
  { country: 'Netherlands', timeZoneId: 'Europe/Amsterdam' },
  { country: 'Belgium', timeZoneId: 'Europe/Brussels' },
  { country: 'Switzerland', timeZoneId: 'Europe/Zurich' },
  { country: 'Portugal', timeZoneId: 'Europe/Lisbon' },
  { country: 'Sweden', timeZoneId: 'Europe/Stockholm' },
  { country: 'Norway', timeZoneId: 'Europe/Oslo' },
  { country: 'Denmark', timeZoneId: 'Europe/Copenhagen' },
  { country: 'Poland', timeZoneId: 'Europe/Warsaw' },
  { country: 'Greece', timeZoneId: 'Europe/Athens' },
  { country: 'Russia', timeZoneId: 'Europe/Moscow' },
  { country: 'United States', timeZoneId: 'America/New_York' },
  { country: 'Canada', timeZoneId: 'America/Toronto' },
  { country: 'Mexico', timeZoneId: 'America/Mexico_City' },
  { country: 'Brazil', timeZoneId: 'America/Sao_Paulo' },
  { country: 'Argentina', timeZoneId: 'America/Argentina/Buenos_Aires' },
  { country: 'Australia', timeZoneId: 'Australia/Sydney' },
  { country: 'New Zealand', timeZoneId: 'Pacific/Auckland' },
  { country: 'South Africa', timeZoneId: 'Africa/Johannesburg' },
  { country: 'Nigeria', timeZoneId: 'Africa/Lagos' },
  { country: 'Kenya', timeZoneId: 'Africa/Nairobi' }
];
